name: Matrix
on: push

jobs:
  node-version:
    runs-on: ubunutu-latest
    steps:
       - name: Log node version
         run: node -v
       - uses: actions/setup-node@1
         with:
           node-version: 6
       - name: Log node version
         run: node -v
